---

#############################
#Copy configuration files
##############################

- name: Create directories if it does not exist
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  with_items: "{{ k8s_dir }}"

#containerd prerequisites, first load two modules and configure them to load on boot
#https://kubernetes.io/docs/setup/production-environment/container-runtimes/

- name: Copy configuration files with owner and permissions
  copy:
    src: "{{ item.src }}" #/srv/myfiles/foo.conf
    dest: "{{ item.dest }}" #/etc/foo.conf
    # owner: root
    # group: root
    mode: '0644'
  with_items: "{{ k8s_config_files }}"  


