---
##############################################
# Main task that executes this ansible role  
##############################################

- name: verify hosts is available
  include_tasks: "00_ping_test.yml"
  
- name: Verify requiremnts 
  include_tasks: "01_requirements.yml"
  
##############################################
# Install necesary packages
##############################################
- name: Deploy cluster 
  include_tasks: "02_deploy_cluster.yml"

##############################################
# Start cluster
##############################################

# - name: Start k8s Cluster
#   include_tasks: "03_create_cluster.yml"     
