###################################
# Install Kubernetes Packages
###################################

#Install Kubernetes packages - kubeadm, kubelet and kubectl
#
- name: Add Google's apt repository gpg key
  command: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"

# - name: Add an Apt signing key, uses whichever key is at the URL
#   ansible.builtin.apt_key:
#     url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
#     state: present


- name: Check if lines already exist in file
  stat: /etc/apt/sources.list.d/kubernetes.list
  register: containerd_lines

- name: Add a line to a file if the file does not exist, without passing regexp
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    insertafter: EOF
    line: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    create: yes
    
  when: containerd_lines.stdout != kubernetes-xenial

# #Add the Kubernetes apt repository
# sudo bash -c 'cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
# deb https://apt.kubernetes.io/ kubernetes-xenial main
# EOF'

- name: Checking the installation of the kubernetes packages
  shell: "dpkg -l | grep kubelet.*"
  register: package_k8s

- name: Update the repository cache
  apt:
    update_cache: yes
  when: package_k8s.rc == 1   

- name: Install kubernetes packages  (state=present is optional)
  apt:
    name: 
      - "kubelet={{ k8s_version }}"
      - "kubeadm={{ k8s_version }}"
      - "kubectl={{ k8s_version }}"
    state: present
  when: package_kbs.rc == 1

- name: hold versions
  command: "apt-mark hold kubelet kubeadm kubectl containerd"

- name: #Ensure both are set to start when the system starts up.
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - kubelet
    - containerd
