##############################################
# Main task that executes this ansible role  
##############################################

- name: verify hosts is available
  include_tasks: "00_ping_test.yml"
  
- name: Verify requiremnts is done 
  include_tasks: "01_requirements.yml"
  
##############################################
# Install necesary packages
##############################################
- name: Verify requiremnts is done 
  include_tasks: "02_install_k8s.yml"

##############################################
# Start cluster
##############################################

# - name: Start k8s Cluster
#   include_tasks: "03_create_cluster.yml"     
